from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

TILE_WIDTH = 280
TILE_HEIGHT = 288
PANEL_WIDTH = 220
GRID_COLS = 4
GRID_ROWS = 4
TOTAL_TILES = GRID_COLS * GRID_ROWS

ACTION_FREQ = 24
DEFAULT_MAX_STEPS = 2048 * 80

DEFAULT_ROM = PROJECT_ROOT / "PokemonRed.gb"
DEFAULT_INIT_STATE = PROJECT_ROOT / "init.state"

REWARD_MODIFIER_PRAISE = 5.0
REWARD_MODIFIER_SLASH = -5.0
